### ISSUE TITLE
Error Details: Didn't get a response from the NVR - connect ECONNREFUSED

### ISSUE THREAD

**Issue by gharshaw** [kushagharahi/homebridge-dahua-alerts#11] opened 2021-02-19 03:34 UTC
I've stepped thru all the recommendations you made with the closed issue #1. I can get postman index results when I use HTTP. It appears to me that you are requiring or sending the call to the NVR with HTTPS. Is there a way to change the config to make the call with HTTP and not HTTPS?
Thanks

**Comment by kushagharahi** [comment] 2021-02-19 04:27
Hi there, could you post some debug logs for me? Definitely possible to add that feature in, although I'm somewhat suspect that is the root cause. My NVR is extremely old and supports both HTTP and HTTPS.

**Comment by gharshaw** [comment] 2021-02-19 04:34
[2/18/2021, 11:30:10 PM] [dahua-alerts] Error Received (for more info enable debug logging)
[2/18/2021, 11:30:10 PM] [dahua-alerts] Error Details: Didn't get a response from the NVR - connect ECONNREFUSED 192.168.10.161:443
[2/18/2021, 11:30:10 PM] [dahua-alerts] Reconnecting in 10s.
[2/18/2021, 11:30:20 PM] [dahua-alerts] Error Received (for more info enable debug logging)
[2/18/2021, 11:30:20 PM] [dahua-alerts] Error Details: Didn't get a response from the NVR - connect ECONNREFUSED 192.168.10.161:443
[2/18/2021, 11:30:20 PM] [dahua-alerts] Reconnecting in 10s.
[2/18/2021, 11:30:30 PM] [dahua-alerts] Error Received (for more info enable debug logging)
[2/18/2021, 11:30:30 PM] [dahua-alerts] Error Details: Didn't get a response from the NVR - connect ECONNREFUSED 192.168.10.161:443
[2/18/2021, 11:30:30 PM] [dahua-alerts] Reconnecting in 10s.
[2/18/2021, 11:30:40 PM] [dahua-alerts] Error Received (for more info enable debug logging)
[2/18/2021, 11:30:40 PM] [dahua-alerts] Error Details: Didn't get a response from the NVR - connect ECONNREFUSED 192.168.10.161:443
[2/18/2021, 11:30:40 PM] [dahua-alerts] Reconnecting in 10s.

**Comment by gharshaw** [comment] 2021-02-19 04:34
I have Homebridge in debug mode - is there a way to create additional debug output with dahua-alerts?

**Comment by kushagharahi** [comment] 2021-02-19 04:41
No that's perfect. I have one other request. Can you look in the networking menus, under connection perhaps for an `Enable https` button? 

It _might_ look something like this.
![image](https://user-images.githubusercontent.com/3326002/108458493-60a49300-723a-11eb-9348-5fc84639ce86.png)

Also, what is your NVR model?

**Comment by kushagharahi** [comment] 2021-02-19 04:42
Two other people had to do the same in the previous issues, such as: https://github.com/kushagharahi/homebridge-dahua-alerts/issues/10#issuecomment-762517347

**Comment by gharshaw** [comment] 2021-02-19 04:44
Just rechecked my NVR and 443 was not enabled. I saw port 443 configured I missed the checkbox to enable it  :-/ - 

Now I am getting a different error 

node:123226) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:123226) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of undefined
    at /usr/lib/node_modules/homebridge-dahua-alerts/src/dahua.ts:87:53
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:123226) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:123226) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by kushagharahi** [comment] 2021-02-19 04:47
Hmm, I doubt this will change anything but could you try restarting homebridge?

**Comment by gharshaw** [comment] 2021-02-19 04:50
Restarted - same error in log

**Comment by gharshaw** [comment] 2021-02-19 04:57
Lorex NR818

**Comment by kushagharahi** [comment] 2021-02-19 04:57
Ok, could you please replace the dist folder contents in homebridge\node_modules\homebridge-dahua-alerts\dist with the contents of this zip and restart? I've added a debug log to see if I can figure out the issue.

[dist.zip](https://github.com/kushagharahi/homebridge-dahua-alerts/files/6007742/dist.zip)

This won't fix the issue, it will just help me diagnose it further.

**Comment by kushagharahi** [comment] 2021-02-19 04:58
Oh and post all the debug logs once you do that please!

**Comment by gharshaw** [comment] 2021-02-19 05:14
[homebridge.log.txt](https://github.com/kushagharahi/homebridge-dahua-alerts/files/6007797/homebridge.log.txt)

**Comment by kushagharahi** [comment] 2021-02-19 05:34
Ok that was really helpful, thanks! Can you try this for me? I think it might fix this specific bug.

[dist.zip](https://github.com/kushagharahi/homebridge-dahua-alerts/files/6007998/dist.zip)

**Comment by gharshaw** [comment] 2021-02-19 14:46
Error is gone and received a motion alert :-)
[homebridge.log.txt](https://github.com/kushagharahi/homebridge-dahua-alerts/files/6010729/homebridge.log.txt)

**Comment by gharshaw** [comment] 2021-02-19 16:11
How quickly should a motion alert on the camera be detected by your plugin?

**Comment by kushagharahi** [comment] 2021-02-19 18:39
>How quickly should a motion alert on the camera be detected by your plugin? 

It is instant as it subscribes to the websocket endpoint provided by your NVR. You can verify this by triggering motion alerts and watching the logs. 
Ensure you have the config for homebridge-camera-ffmpeg setup correctly. Specifically make sure to set motionTimeout to 0.

I just pushed version 1.1.2, could you please install it and verify it works as well?

**Comment by gharshaw** [comment] 2021-02-19 20:07
Installed 1.1.2 and it works as well.  I appreciate the plugin and the help. Enjoy the coffee :-)
[homebridge.log.txt](https://github.com/kushagharahi/homebridge-dahua-alerts/files/6012665/homebridge.log.txt)

**Comment by kushagharahi** [comment] 2021-02-20 00:19
Thanks for testing the latest version and verifying that it's working! Coffee is much appreciated as well 😄 

If you run into any other problems please don't hesitate to open another issue!

**Closed as completed by kushagharahi** 2021-02-20 00:19 UTC
